name: Build and Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-integrate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.18.2]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install yalc globally
        run: yarn global add yalc

      - name: Install dependencies
        run: yarn install

      - name: Run build-and-integrate script
        run: yarn build-and-integrate
